### ISSUE TITLE
grid and modules file size are too big

### ISSUE THREAD

**Issue by Coss0022** [Coss0022/fastness-fixer#1]
Can't seem to figure out how to make the file sizes smaller. Tried to take out unnecessary code and it's still too big. 

@charlie-quinn

**Comment by charlie-quinn** [comment]
After going through and removing settings in both of these files, we need to manually go in and remove some extra classes:
- [ ] [checkout the difference between your grid (on the left) and the grid with extra classes removed (on the right)](https://www.diffchecker.com/xOmdTmL5)
- [ ] [checkout the difference between your modules (on the left) and the modules with extra classes removed (on the right)](https://www.diffchecker.com/cVMdjBwK)

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
